sudo: false

language: python

python:
  - 3.6.0

cache: pip

env:
  global:
  - USER="ndip007"
  - EMAIL="owenhojunior@gmail.com"
  - REPO="py_project"
  - FILES="README.md npm_project-build-tool-rdf.spdx npm_project-build-tool-tv.spdx"
  - GH_REPO="github.com/${USER}/${REPO}.git"
  
install:
  - pip install -e git+https://github.com/ndip007/spdx-build-tool#egg=spdx-build-tool

script:
  - spdx-build $TRAVIS_BUILD_DIR
 
after_success:
  - git clone https://github.com/ndip007/py_project.git
  - mv -f "README.md npm_project-build-tool-rdf.spdx npm_project-build-tool-tv.spdx" "py_project"
  - cd py_project
  - git remote
  - git config user.email "owenhojunior@gmail.com"
  - git config user.name "ndip007"
  - git add "README.md npm_project-build-tool-rdf.spdx npm_project-build-tool-tv.spdx"
  - git commit -m "commit spdx iles"
  - git push "https://$TRAVIS_SECURE_TOKEN_NAME@github.com/ndip007/py_project.git" master > /dev/null 2>&1
